<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>50814b00-1a0b-44e1-b421-f07c03e19f68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SidebarContent > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SidebarContent']/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#SidebarContent >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5d738007-cc3d-4a2f-ae22-5334938d4916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/fish_icon.gif</value>
      <webElementGuid>e2d1b0fc-3d36-4ee9-8125-cbebf0c439a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SidebarContent&quot;)/a[1]/img[1]</value>
      <webElementGuid>527ffb4c-a497-4c65-8b57-c8c056901925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SidebarContent']/a/img</value>
      <webElementGuid>8e4cc8bd-67a1-47a1-9e80-4a2d15a5beaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>be7e8ea3-5bbf-4eee-a523-92fd5b74d317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/fish_icon.gif']</value>
      <webElementGuid>8c2d9b4e-8892-400a-87af-c410a3669cda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
