<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign In</name>
   <tag></tag>
   <elementGuidId>7222c62e-0197-467d-b8e3-eabfd953d402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MenuContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MenuContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sign In ?&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>913d3bb3-db80-4c57-ad23-ee319a0cf2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MenuContent</value>
      <webElementGuid>495f1e04-e60f-49c1-92f8-ecd2095944e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  
	Sign In
    ?</value>
      <webElementGuid>3181d075-e29a-4ac1-a8c5-4416ef644904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MenuContent&quot;)</value>
      <webElementGuid>d80282e3-2b3b-466f-8bdd-9450681347bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='MenuContent']</value>
      <webElementGuid>a9a2061f-9a1f-440a-87b8-843e01dbd6ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Menu']/div</value>
      <webElementGuid>9ec61b62-b5f1-40de-9323-5f9d19878387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>356ff0a1-9282-4503-acfa-159741bd75ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'MenuContent' and (text() = '  
	Sign In
    ?' or . = '  
	Sign In
    ?')]</value>
      <webElementGuid>8c45c793-c621-48c3-81f0-d48eddc405ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
